config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :phonebooks
  root 'phonebooks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phonebook.rb
class Phonebook < ApplicationRecord
    # validates :user_id, presence: true
    #validates :name, presence: {message: "Name cannot be blank."}, on: create
    #validates :number, presence: true, numericality: { only_integer: true }, length: { minimum: 10 }

     #validates :name, :presence => {message: "Name cannot be blank."}, :on => :create
    #validates :number, :presence => {message: "Number content cannot be blank."}, :length => { :minimum => 2, message: "Number is too short."}, :on => :create
    
    validates :user_id, presence: true
    validates :name, presence: {message: "Name cannot be blank."}
    validates :number, presence: {message: "Number content cannot be blank."}, numericality: { only_integer: true , message: "Number must be integer."}, length: { minimum: 10 }

end

app/controllers/phonebooks_controller.rb
class PhonebooksController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @roles = User.roles

        if current_user.role == "admin"
            @phonebook = Phonebook.all
        else
            @phonebook = Phonebook.where(user_id: current_user.id).order(created_at: :desc)
        end
    end

    def new
        @phonebook = Phonebook.new
    end

    def edit
        @phonebook = Phonebook.find(params[:id])
    end

    def create
        @phonebook = Phonebook.new(phonebook_params)
        
        respond_to do |format|
            @errorName = []
            @errorNumber = []
            if @phonebook.save
                format.js
                redirect_to phonebooks_path
            else
                format.js
                @phonebook.errors.any?
                if (@phonebook.errors["name"] != nil)
                    @errorName.push(@phonebook.errors["name"][0])
                end
                if (@phonebook.errors["number"] != nil)
                    @errorNumber.push(@phonebook.errors["number"][0])
                end
            end
        end
    end

    def update
        @phonebook = Phonebook.find(params[:id])
        # if @phonebook.update(phonebook_params)
            
        #     redirect_to phonebooks_path
        # else
        #     render 'edit'
        # end

        respond_to do |format|
            @errorName = []
            @errorNumber = []
            if @phonebook.update(phonebook_params)
                #format.html { redirect_to phonebooks_path }
                format.js { redirect_to phonebooks_path }
            else
                format.js
                @phonebook.errors.any?
                if (@phonebook.errors["name"] != nil)
                    @errorName.push(@phonebook.errors["name"][0])
                end
                if (@phonebook.errors["number"] != nil)
                    @errorNumber.push(@phonebook.errors["number"][0])
                end
                #render 'edit'
            end
        end
    end

    def show
        @phonebook = Phonebook.find(params[:id])
    end

    def destroy
        @phonebook = Phonebook.find(params[:id])
        @phonebook.destroy
     
        redirect_to phonebooks_path
    end

    private
    def phonebook_params
        params.require(:phonebook).permit(:user_id, :name, :number)
    end
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/views/phonebooks/_form.html.erb
<%= form_with model: @phonebook do |form|%>
 
  <%-# COMMENT -%>
  <% if @phonebook.errors.any? false %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@phonebook.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @phonebook.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, required: true, class: 'form-control' %>
    <span id = "nameBlock" class="help-block"></span>
  </p>

  <p>
    <%= form.label :number %><br>
    <%= form.text_field :number, required: true, class: 'form-control' %>
    <span id = "numberBlock" class="help-block"></span>
  </p>
  
  <p>
    <%= form.submit 'Submit', class: 'btn btn-primary btn-md btn-block' %>
  </p>

<% end %>

app/views/phonebooks/create.js.erb
//remove old validation messages
$(".notice").remove();
//remove old instances of the .has-error class
$(".form-group").removeClass("has-error");
 
//display new validation messages and add the Bootstrap .has-error class
$("#nameBlock").append('<div class="notice"><%= escape_javascript(@errorName[0])%></div>');
$("#nameBlock:contains(.)").closest(".form-group").addClass("has-error");
$("#numberBlock").append('<div class="notice"><%= escape_javascript(@errorNumber[0])%></div>');
$("#numberBlock:contains(.)").closest(".form-group").addClass("has-error");

app/views/phonebooks/edit.html.erb
<center><h1>Edit number</h1></center>
<%= render 'form' %>
<%= link_to 'Back', phonebooks_path, class: 'btn btn-default btn-md btn-block' %>

<span id="helpBlock" class="help-block"></span>

app/views/phonebooks/index.html.erb
<% if user_signed_in? %>
  <div class="row">
      <%= link_to '+ Add Contact', new_phonebook_path %> |
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </div>

  <div class="row table-responsive">
    <table class="table table-bordered text-centered">
      <tr>
        <th class=col-md-1>No</th>
        <th class=col-md-4>Name</th>
        <th class=col-md-4>Number</th>
        <th class=col-md-3>Options</th>
      </tr>

      <% no = 1 %>
      <% @phonebook.each do |phonebook| %>
        <tr>
          <td><%= no %></td>
          <td><%= phonebook.name %></td>
          <td><%= phonebook.number %></td>
          <td>
            <%= link_to 'Edit', edit_phonebook_path(phonebook), class: 'btn btn-success btn-xs' %>
            <%= link_to 'Destroy', phonebook_path(phonebook), class: 'btn btn-danger btn-xs',
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% no = no + 1 %>
      <% end %>
    </table>
  </div>

<!--p>User Id : <%= current_user.id %><p-->
<!--p>User Role : <%= current_user.role %></p-->
<% end %>
    

app/views/phonebooks/new.html.erb
<div class="row">
    <center><h1>New Contact</h1></center>
</div>

<%= render 'form' %>

<%= link_to 'Back', phonebooks_path, class: 'btn btn-default btn-md btn-block' %>

<span id="helpBlock" class="help-block"></span>

app/views/phonebooks/update.js.erb
//remove old validation messages
$(".notice").remove();
//remove old instances of the .has-error class
$(".form-group").removeClass("has-error");
 
//display new validation messages and add the Bootstrap .has-error class
$("#nameBlock").append('<div class="notice"><%= escape_javascript(@errorName[0])%></div>');
$("#nameBlock:contains(.)").closest(".form-group").addClass("has-error");
$("#numberBlock").append('<div class="notice"><%= escape_javascript(@errorNumber[0])%></div>');
$("#numberBlock:contains(.)").closest(".form-group").addClass("has-error");